# Generated by Django 4.1.3 on 2022-11-29 18:20

import TourAwesomeApps.Tours.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('startDate', models.DateField()),
                ('specialNote', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=1000)),
                ('highlight', models.CharField(max_length=1000)),
                ('timeline', models.FileField(null=True, upload_to=TourAwesomeApps.Tours.models.tour_timeline_path)),
                ('isDomestic', models.BooleanField(default=True)),
                ('duration_days', models.PositiveIntegerField()),
                ('duration_nights', models.PositiveIntegerField()),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2022, 11, 30, 1, 20, 31, 668664))),
                ('isHot', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TourVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(choices=[('TRAIN', 'Tàu hỏa'), ('PLANE', 'Máy bay'), ('COACH', 'Xe khách'), ('SHIP', 'Thuyền')], max_length=6)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tours.tour')),
            ],
        ),
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=TourAwesomeApps.Tours.models.tour_image_path)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tours.tour')),
            ],
        ),
    ]
