# Generated by Django 4.1.3 on 2022-11-26 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tour',
            table=None,
        ),
    ]
