# Generated by Django 4.1.3 on 2022-11-26 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0002_alter_tour_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tourimage',
            table=None,
        ),
    ]
