# Generated by Django 4.1.3 on 2022-11-28 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0003_alter_tourimage_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(choices=[('TRAIN', 'Tàu hỏa'), ('PLANE', 'Máy bay'), ('COACH', 'Xe khách'), ('SHIP', 'Thuyền')], max_length=6)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tours.tour')),
            ],
        ),
    ]
