# Generated by Django 4.1.3 on 2022-11-28 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0004_tourvehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 28, 13, 43, 16, 46369)),
        ),
    ]
