# Generated by Django 4.1.3 on 2022-11-30 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0005_alter_tour_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='old_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 0, 23, 3, 563097)),
        ),
    ]
