# Generated by Django 4.1.3 on 2022-11-28 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0006_alter_tour_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='isHot',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 28, 14, 58, 49, 970386)),
        ),
    ]
