# Generated by Django 4.1.3 on 2022-12-01 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0008_alter_tour_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='tour',
            name='detailLocation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 13, 57, 41, 656308)),
        ),
    ]
