# Generated by Django 4.1.3 on 2022-11-28 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0008_alter_tour_pub_date_alter_tour_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 28, 20, 16, 24, 62124)),
        ),
    ]
