# Generated by Django 4.1.3 on 2022-12-01 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0009_tourlocation_tour_detaillocation_alter_tour_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourlocation',
            name='numTours',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 13, 59, 26, 778978)),
        ),
    ]
