# Generated by Django 4.1.3 on 2022-12-08 02:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0021_alter_tour_detaillocation_alter_tour_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 8, 9, 38, 52, 267855)),
        ),
        migrations.AlterField(
            model_name='tourlocation',
            name='location',
            field=models.CharField(max_length=50),
        ),
    ]
