# Generated by Django 4.1.3 on 2022-12-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0024_alter_tour_old_price_alter_tour_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
