# Generated by Django 4.1.3 on 2022-12-09 17:01

import TourAwesomeApps.Tours.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0025_alter_tour_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourlocation',
            name='image',
            field=models.ImageField(null=True, upload_to=TourAwesomeApps.Tours.models.location_image_path),
        ),
    ]
