# Generated by Django 4.1.3 on 2022-12-12 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0026_tourlocation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='bookingCount',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
