# Generated by Django 4.1.3 on 2022-12-17 04:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tours', '0029_review_rating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('tour', 'user')},
        ),
    ]
