# Generated by Django 4.1.3 on 2022-12-17 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0030_alter_review_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='startLocation',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
