# Generated by Django 4.1.3 on 2022-12-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0031_tour_startlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='ratingsAverage',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='ratingsQuantity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
