# Generated by Django 4.1.3 on 2022-12-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0034_remove_tour_ratingsquantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='ratingsQuantity',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
