# Generated by Django 4.1.3 on 2022-11-27 05:20

import TourAwesomeApps.Blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.FileField(upload_to=TourAwesomeApps.Blogs.models.blog_content_path)),
            ],
        ),
    ]
