# Generated by Django 4.1.3 on 2022-12-07 09:23

import TourAwesomeApps.Blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0002_blog_relatedlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(null=True, upload_to=TourAwesomeApps.Blogs.models.blog_image_path),
        ),
    ]
