# Generated by Django 4.1.3 on 2022-11-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phoneNum',
            field=models.BigIntegerField(null=True),
        ),
    ]
