# Generated by Django 4.1.3 on 2022-11-30 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='isMale',
        ),
        migrations.AddField(
            model_name='myuser',
            name='sex',
            field=models.CharField(choices=[('MALE', 'Nam'), ('FEMALE', 'Nữ')], max_length=6, null=True),
        ),
    ]
