# Generated by Django 4.1.3 on 2022-11-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_remove_myuser_ismale_myuser_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='sex',
            field=models.CharField(choices=[('MALE', 'Nam'), ('FEMALE', 'Nữ')], default=('MALE', 'Nam'), max_length=6, null=True),
        ),
    ]
