# Generated by Django 4.1.3 on 2022-11-26 10:13

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_myuser_managers_alter_myuser_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='phoneNum',
            field=models.CharField(default=0, max_length=11),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
