# Generated by Django 4.1.3 on 2022-12-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_myuser_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='sex',
            field=models.CharField(choices=[('MALE', 'Nam'), ('FEMALE', 'Nữ')], max_length=6, null=True),
        ),
    ]
