# Generated by Django 4.1.3 on 2022-12-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_myuser_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='startDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
