# Generated by Django 4.1.3 on 2022-11-27 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_myuser_managers_alter_myuser_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='role',
        ),
    ]
