# Generated by Django 4.1.3 on 2022-11-27 14:11

import TourAwesomeApps.Users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_remove_myuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(default='users/user-profile.png', upload_to=TourAwesomeApps.Users.models.user_image_path),
        ),
    ]
